"""Browser integration checks. Install Playwright separately: pip install playwright.
Normal: python tests/browser-smoke.py --url http://127.0.0.1:8787
Restricted/opaque-origin fallback QA: python tests/browser-smoke.py --injected
The injected mode does not validate WebGPU, browser workers, or native file access.
"""
import argparse, asyncio, base64, json, os, time
from pathlib import Path
from playwright.async_api import async_playwright
ROOT = Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser()
parser.add_argument('--url',default='http://127.0.0.1:8787')
parser.add_argument('--injected',action='store_true')
parser.add_argument('--browser',default=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'))
args=parser.parse_args()
results=[]
def check(name,condition,detail=None):
    if not condition: raise AssertionError(f'{name}: {detail}')
    results.append({'name':name,'passed':True})
async def main():
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path=args.browser,headless=True,args=['--no-sandbox'])
  ctx=await browser.new_context(viewport={'width':1280,'height':850},device_scale_factor=1,accept_downloads=True)
  page=await ctx.new_page();errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  async def load(pg):
   if args.injected: await pg.set_content((ROOT/'NotepadXP.html').read_text(),wait_until='load')
   else: await pg.goto(args.url,wait_until='networkidle')
   await pg.wait_for_function('window.notepad !== undefined')
   await pg.evaluate('notepad.ready')
  await load(page)
  async def tool(toolname,**kwargs):return await page.evaluate('([n,a])=>notepad.execute(n,a)',[toolname,kwargs])
  async def state():return await page.evaluate('notepad.getState()')
  async def text():return (await tool('document_read',length=262144))['text']
  async def reset(s,name='Notes.txt'):
   await tool('document_set_text',text=s,name=name,discardChanges=True)
   await tool('view_set_options',wordWrap=False,statusBar=False,fontFamily='Lucida Console',fontSize=10,fontStyle='Regular')
   await tool('view_goto',line=1)
  initial=await state()
  check('Application starts with all 24 automation tools',len(await page.evaluate('notepad.getTools()'))==24)
  await page.locator('#text-input').focus()
  await page.keyboard.type('Notepad XP\nA familiar place for your thoughts.\n\nPlain text, carefully crafted.\n')
  check('Native keyboard typing updates the real document',(await text()).startswith('Notepad XP\nA familiar'))
  await page.keyboard.press('Control+Home');await page.keyboard.press('Control+f')
  await page.locator('#find-query').fill('familiar');await page.locator('[data-action="findNext"]').click()
  await page.wait_for_timeout(80)
  s=await state();check('Find dialog selects a literal match',s['selection']['end']-s['selection']['start']==8,s)
  await page.screenshot(path=str(ROOT/'docs/find-dialog.png'))
  await page.locator('[data-action="cancel"]').click()
  await page.keyboard.press('Control+h');await page.locator('#find-query').fill('text');await page.locator('#replace-text').fill('words')
  await page.locator('[data-action="replaceAll"]').click();await page.wait_for_timeout(80)
  check('Replace All dialog changes document','Plain words' in await text())
  await page.locator('[data-action="cancel"]').click();await tool('edit_undo')
  check('Replace All undoes as a single operation','Plain text' in await text())
  await tool('edit_redo');check('Redo restores replacement','Plain words' in await text())
  await page.keyboard.press('Control+g');await page.locator('#goto-line').fill('3');await page.locator('[data-action="go"]').click()
  check('Go To dialog uses one-based logical lines',(await state())['cursor']['line']==3)
  await tool('ui_command',command='statusBar');check('Status Bar can be shown',(await state())['view']['statusBarVisible'])
  await tool('ui_command',command='wordWrap');check('XP Word Wrap hides Status Bar',not (await state())['view']['statusBarVisible'])
  await page.locator('#menubar button').nth(1).click()
  check('Word Wrap disables classic Go To',await page.locator('[data-command="goto"]').is_disabled())
  await page.keyboard.press('Escape');await tool('ui_command',command='wordWrap')
  await tool('ui_command',command='font');await page.locator('#font-family').fill('Courier New');await page.locator('#font-size').fill('12')
  await page.screenshot(path=str(ROOT/'docs/font-dialog.png'))
  await page.locator('[data-action="ok"]').click();check('Font dialog applies font and point size',(await state())['view']['fontSize']==12)
  await tool('ui_command',command='pageSetup');await page.locator('#page-header').fill('&l&f&r&p');await page.locator('#page-paper').select_option('A4');await page.locator('[data-action="ok"]').click()
  check('Page Setup retains paper and header commands',(await state())['pageSetup']['paper']=='A4')
  await reset('first\nsecond\nthird\n')
  await page.keyboard.press('Control+Home');await page.keyboard.press('Shift+End');await page.keyboard.type('FIRST')
  check('Shift navigation and replacement edit correctly',(await text()).startswith('FIRST\n'))
  await page.keyboard.press('Control+End');await page.keyboard.press('F5');check('F5 inserts local time and date',len(await text())>30)
  await reset('ab📝cd\n')
  await tool('view_goto',line=1,column=5);await page.locator('#text-input').focus();await page.keyboard.press('Backspace')
  check('Backspace removes an entire surrogate-pair grapheme',await text()=='abcd\n',await text())
  await reset('<script>window.hacked=1</script>\nZażółć gęślą jaźń\n日本語 📝\n')
  check('Document markup is inert',await page.evaluate('window.hacked === undefined'))
  exported=await tool('document_export',encoding='utf-16be',eol='CRLF',bom=True)
  raw=base64.b64decode(exported['data']);check('Unicode big endian export has BOM and CRLF',raw[:2]==b'\xfe\xff' and b'\x00\r\x00\n' in raw)
  await tool('document_open_base64',data=exported['data'],name='Unicode.txt',discardChanges=True)
  check('Encoded import round-trips Unicode','Zażółć' in await text() and (await state())['encoding']=='utf-16be')
  await tool('document_open_base64',data=base64.b64encode(b'.LOG\r\n').decode(),name='Journal.txt',discardChanges=True)
  check('.LOG files append a timestamp and become modified',(await text()).startswith('.LOG\n\n') and (await state())['modified'])
  revision=(await state())['revision']
  await tool('document_apply_edits',edits=[{'start':0,'end':4,'text':'JOURNAL'}],expectedRevision=revision)
  stale=await page.evaluate('async r=>{try{await notepad.execute("document_insert",{text:"BAD",expectedRevision:r});return false}catch(e){return e.message.includes("Revision")}}',revision)
  check('Stale agent edits are rejected without mutation',stale and not (await text()).endswith('BAD'))
  await tool('ui_command',command='new');await page.wait_for_timeout(20)
  check('New protects unsaved text with a confirmation',(await state())['dialog'] is not None)
  await tool('ui_dialog',action='click',control='cancel');await page.wait_for_timeout(20)
  check('Cancel preserves dirty document',(await text()).startswith('JOURNAL'))
  await tool('ui_command',command='saveAs');await page.wait_for_selector('#file-name')
  await page.locator('#file-name').fill('Journal.txt');await page.locator('#file-encoding').select_option('utf-8')
  await page.screenshot(path=str(ROOT/'docs/save-as-dialog.png'))
  check('Save As exposes all four classic encodings',await page.locator('#file-encoding option').count()==4)
  await tool('ui_dialog',action='close')
  await tool('ui_command',command='about');check('About dialog is populated','About' in (await state())['dialog']['title']);await tool('ui_dialog',action='close')
  await tool('ui_command',command='help');check('Help dialog has real documentation',await page.locator('.xp-dialog').inner_text()!='');await tool('ui_dialog',action='close')
  await tool('ui_command',command='agent');check('Agent dialog is disabled until user authorization',not (await state())['agent']['enabled']);await tool('ui_dialog',action='close')
  await tool('ui_command',command='maximize');check('Maximize changes window state',(await state())['view']['maximized'])
  await tool('ui_command',command='restore');check('Restore exits maximized state',not (await state())['view']['maximized'])
  await tool('ui_command',command='minimize');check('Minimize shows task button',await page.locator('#restore-window').is_visible());await page.locator('#restore-window').click()
  await reset('A line with enough text to wrap repeatedly across a narrow viewport. '*3000)
  await tool('view_set_options',wordWrap=True);await page.wait_for_timeout(450)
  check('Long text creates wrapped visual rows',(await state())['view']['visualRows']>100)
  await tool('view_set_options',wordWrap=False)
  large=await page.evaluate('async()=>{const t=performance.now();await notepad.execute("document_set_text",{text:"0123456789 abcdefghijklmnopqrstuvwxyz\\n".repeat(200000),name:"Large.txt",discardChanges:true});await notepad.execute("view_goto",{line:200000});await new Promise(requestAnimationFrame);return {loadAndGotoMs:performance.now()-t,state:notepad.getState(),metrics:notepad.getMetrics(),elements:document.querySelectorAll("*").length,proxyLength:document.querySelector("#text-input").value.length}}')
  check('200,001 logical lines remain viewport-sized',large['state']['lineCount']==200001 and large['elements']<200 and large['proxyLength']<10000,large)
  await page.screenshot(path=str(ROOT/'docs/large-document.png'))
  longline=await page.evaluate('async()=>{const t=performance.now();await notepad.execute("document_set_text",{text:"x".repeat(5000000),name:"Long-line.txt",discardChanges:true});await notepad.execute("view_goto",{line:1,column:4999999});await new Promise(requestAnimationFrame);return {ms:performance.now()-t,state:notepad.getState(),metrics:notepad.getMetrics()}}')
  check('Five-million-character line scrolls to its caret',longline['state']['cursor']['column']==4999999 and longline['state']['view']['scrollX']>1000000,longline)
  await reset('Notepad XP\n\nA familiar place for your thoughts.\n\nFile  Edit  Format  View  Help\n\nPlain text, carefully crafted.\n\nSave as ANSI, Unicode, Unicode big endian, or UTF-8.\nUse Find, Replace, Go To, and the classic Font dialog.\n\nCtrl+Alt+M opens optional local AI agent control.\n')
  await tool('view_set_options',statusBar=True);await tool('view_goto',line=1);await page.screenshot(path=str(ROOT/'docs/desktop.png'))
  await page.locator('#menubar button').nth(1).click();await page.screenshot(path=str(ROOT/'docs/edit-menu.png'));await page.keyboard.press('Escape')
  await tool('ui_command',command='print');await page.wait_for_timeout(200)
  printInfo=await page.evaluate('(()=>{const d=document.querySelector("#print-frame").contentDocument;return {pages:d.querySelectorAll(".page").length,text:d.body.innerText}})()')
  check('Print preparation produces paginated text and header',printInfo['pages']>=1 and 'Notepad XP' in printInfo['text'])
  check('Desktop browser execution has no uncaught errors',not errors,errors)
  mobilectx=await browser.new_context(viewport={'width':390,'height':844},device_scale_factor=2,is_mobile=True,has_touch=True)
  mobile=await mobilectx.new_page();await load(mobile)
  await mobile.evaluate('notepad.execute("document_set_text",{text:"Notepad XP on the go.\\n\\nTap to place the cursor.\\nPress and hold to select a word.\\nDrag the handles to adjust selection.\\n\\nThe same familiar menus, wherever you write.",name:"Mobile.txt",discardChanges:true})')
  await mobile.evaluate('notepad.execute("view_set_options",{wordWrap:true})')
  await mobile.locator('#editor').tap(position={'x':45,'y':30});await mobile.wait_for_timeout(100)
  geom=await mobile.evaluate('({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,window:document.querySelector("#window").getBoundingClientRect().toJSON(),state:notepad.getState()})')
  check('Touch viewport fits 390px without horizontal page overflow',geom['scrollWidth']<=390 and geom['window']['width']<=390,geom)
  await mobile.screenshot(path=str(ROOT/'docs/mobile.png'))
  await mobile.locator('#menubar button').nth(2).tap();await mobile.locator('[data-command="font"]').tap();await mobile.screenshot(path=str(ROOT/'docs/mobile-font.png'))
  box=await mobile.locator('.xp-dialog').bounding_box();check('Font dialog fits mobile viewport',box['width']<=390,box)
  report={'mode':'injected opaque-origin fallback' if args.injected else 'localhost navigation','browser':browser.version,'renderer':initial['renderer'],'worker':initial['worker'],'webgpuValidated':initial['renderer']=='WebGPU','checks':results,'largeDocument':large,'longLine':longline,'uncaughtErrors':errors,'limitations':['Native OS file pickers, actual disk writes, system printing, and physical mobile keyboards are not automated by this test.']}
  (ROOT/'docs/browser-test-results.json').write_text(json.dumps(report,indent=2))
  print(json.dumps({'passed':len(results),'renderer':initial['renderer'],'worker':initial['worker'],'largeDocumentMs':large['loadAndGotoMs'],'longLineMs':longline['ms'],'errors':errors},indent=2))
  await browser.close()
asyncio.run(main())
