import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {createNotepadServer} from '../mcp/server.mjs';
import {TextModel} from '../src/model.mjs';
const TOKEN='test-notepad-token-0123456789abcdef';
let app;
test.before(async()=>{app=await createNotepadServer({port:0,token:TOKEN,quiet:true});});
test.after(async()=>{await app.close();});
const auth={Authorization:`Bearer ${TOKEN}`};
const headers={...auth,'Content-Type':'application/json',Accept:'application/json, text/event-stream'};
async function initialize(){const response=await fetch(app.url+'/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'tests',version:'1'}}})});const packet=await response.json(),session=response.headers.get('mcp-session-id');assert.equal(packet.result.protocolVersion,'2025-11-25');assert.ok(session);const h={...headers,'Mcp-Session-Id':session,'MCP-Protocol-Version':'2025-11-25'};const initialized=await fetch(app.url+'/mcp',{method:'POST',headers:h,body:JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'})});assert.equal(initialized.status,202);return{headers:h,session};}
async function rpc(h,method,params={},id=2){const r=await fetch(app.url+'/mcp',{method:'POST',headers:h,body:JSON.stringify({jsonrpc:'2.0',id,method,params})});return{status:r.status,packet:await r.json()};}
async function bridge(path,data,key){const response=await fetch(app.url+'/bridge/'+path,{method:data===undefined?'GET':'POST',headers:{...auth,...(key?{'X-Notepad-Tab-Key':key}:{}),...(data!==undefined?{'Content-Type':'application/json'}:{})},body:data===undefined?undefined:JSON.stringify(data)});return{status:response.status,data:await response.json()};}
test('static app has CSP and no token embedded in HTML',async()=>{const r=await fetch(app.url+'/');assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal((await r.text()).includes(TOKEN),false);});
test('server and test files are not exposed through the static route',async()=>{for(const p of ['/mcp/server.mjs','/package.json','/../etc/passwd','/src/%2e%2e/mcp/server.mjs'])assert.equal((await fetch(app.url+p)).status,404);});
test('HTTP MCP requires bearer authentication',async()=>{const r=await fetch(app.url+'/mcp',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,401);});
test('untrusted origins and forged Host headers are rejected',async()=>{const r=await fetch(app.url+'/mcp',{method:'POST',headers:{...headers,Origin:'https://evil.example'},body:'{}'});assert.equal(r.status,403);const status=await new Promise((resolve,reject)=>{const req=http.get(app.url+'/',{headers:{Host:'evil.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);});assert.equal(status,403);});
test('initialization, tools/list, and resource discovery',async()=>{const client=await initialize();const {packet}=await rpc(client.headers,'tools/list');assert.equal(packet.result.tools.length,24);const resources=await rpc(client.headers,'resources/list');assert.equal(resources.packet.result.resources.length,3);});
test('unknown methods return a JSON-RPC method error',async()=>{const client=await initialize();const r=await rpc(client.headers,'shell/execute');assert.equal(r.packet.error.code,-32601);});
test('unsupported HTTP method, wrong Accept, and missing sessions are rejected',async()=>{assert.equal((await fetch(app.url+'/mcp',{headers:auth})).status,405);assert.equal((await fetch(app.url+'/mcp',{method:'POST',headers:{...headers,Accept:'application/json'},body:'{}'})).status,406);assert.equal((await fetch(app.url+'/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'})})).status,400);});
test('tool validation and absence of an authorized tab return tool errors',async()=>{const c=await initialize();const invalid=await rpc(c.headers,'tools/call',{name:'document_read',arguments:{length:999999999}});assert.equal(invalid.packet.result.isError,true);const missing=await rpc(c.headers,'tools/call',{name:'app_get_state',arguments:{}});assert.equal(missing.packet.result.isError,true);assert.match(missing.packet.result.content[0].text,/No browser tab/);});
test('paired browser round-trip carries actual document edits and results',async()=>{const c=await initialize(),tabId='test-browser-full-control';const pair=await bridge('connect',{tabId,readOnly:false,state:{name:'test.txt',length:3,revision:0}});assert.equal(pair.status,200);const key=pair.data.tabKey;assert.ok(key);
 const model=new TextModel('abc');const pending=rpc(c.headers,'tools/call',{name:'document_insert',arguments:{text:'XYZ',position:1,tabId}},20);
 const poll=await bridge('poll?tabId='+tabId,undefined,key);assert.equal(poll.status,200);const job=poll.data.commands[0];assert.equal(job.name,'document_insert');model.edit(job.arguments.position,job.arguments.position,job.arguments.text);
 await bridge('result',{tabId,id:job.id,result:{text:model.slice(),revision:model.revision}},key);const response=await pending;assert.equal(response.packet.result.isError,false);assert.equal(response.packet.result.structuredContent.text,'aXYZbc');
 const listed=await rpc(c.headers,'tools/call',{name:'app_list_tabs',arguments:{}});assert.equal(listed.packet.result.structuredContent.tabs[0].name,'test.txt');assert.equal(JSON.stringify(listed).includes(key),false);
 assert.equal((await bridge('state',{tabId,state:{}},'wrong-key')).status,403);await bridge('disconnect',{tabId},key);
});
test('read-only grants are enforced by the server, not just by the UI',async()=>{const c=await initialize(),tabId='test-browser-read-only';const pair=await bridge('connect',{tabId,readOnly:true,state:{name:'read.txt'}});const result=await rpc(c.headers,'tools/call',{name:'document_insert',arguments:{text:'bad',tabId}});assert.equal(result.packet.result.isError,true);assert.match(result.packet.result.content[0].text,/read-only/);await bridge('disconnect',{tabId},pair.data.tabKey);});
test('MCP session deletion is honored',async()=>{const c=await initialize();assert.equal((await fetch(app.url+'/mcp',{method:'DELETE',headers:c.headers})).status,204);assert.equal((await rpc(c.headers,'ping')).status,404);});
test('stdio protocol emits JSON-RPC only and negotiates an older revision',async()=>{
 const child=spawn(process.execPath,[fileURLToPath(new URL('../mcp/server.mjs',import.meta.url)),'--stdio','--port','0'],{env:{...process.env,NOTEPAD_TOKEN:TOKEN},stdio:['pipe','pipe','pipe']});let buffer='',stderr='';const waiters=[];child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');child.stderr.on('data',d=>stderr+=d);child.stdout.on('data',chunk=>{buffer+=chunk;let at;while((at=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,at);buffer=buffer.slice(at+1);if(line)waiters.shift()?.resolve(JSON.parse(line));}});
 const request=message=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('stdio test timeout')),10000);waiters.push({resolve:v=>{clearTimeout(timer);resolve(v);}});child.stdin.write(JSON.stringify(message)+'\n');});
 try{const init=await request({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'test',version:'1'}}});assert.equal(init.result.protocolVersion,'2025-03-26');child.stdin.write(JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'})+'\n');const list=await request({jsonrpc:'2.0',id:2,method:'tools/list'});assert.equal(list.result.tools.length,24);assert.match(stderr,/Open: http:\/\/127.0.0.1:/);}finally{child.stdin.end();await new Promise(resolve=>child.once('exit',resolve));}
});
